package com.mycompany.vbinarysearchtree;

/**
 *
 * @author skyla
 */
public class MainWindow extends javax.swing.JFrame {
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        MainWindow_Panel_Graph = new GraphicsPanelTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainWindow_TextFiels_AddNum = new javax.swing.JTextField();
        MainWindow_Label_Warning = new javax.swing.JLabel();
        MainWindow_Button_ShowTable = new javax.swing.JButton();
        MainWindow_Panel_Graph = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainWindow_TextFiels_AddNum.setText("70 80 85 90 98 100 120");
        MainWindow_TextFiels_AddNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_TextFiels_AddNumActionPerformed(evt);
            }
        });

        MainWindow_Label_Warning.setText("<- ALL Numbers Here");

        MainWindow_Button_ShowTable.setText("Show Table ");
        MainWindow_Button_ShowTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_Button_ShowTableActionPerformed(evt);
            }
        });

        MainWindow_Panel_Graph.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainWindow_Panel_GraphLayout = new javax.swing.GroupLayout(MainWindow_Panel_Graph);
        MainWindow_Panel_Graph.setLayout(MainWindow_Panel_GraphLayout);
        MainWindow_Panel_GraphLayout.setHorizontalGroup(
            MainWindow_Panel_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        MainWindow_Panel_GraphLayout.setVerticalGroup(
            MainWindow_Panel_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(MainWindow_Button_ShowTable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainWindow_TextFiels_AddNum, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainWindow_Label_Warning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(MainWindow_Panel_Graph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(MainWindow_Panel_Graph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainWindow_TextFiels_AddNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainWindow_Button_ShowTable)
                    .addComponent(MainWindow_Label_Warning))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainWindow_TextFiels_AddNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_TextFiels_AddNumActionPerformed
    String data = MainWindow_TextFiels_AddNum.getText();

    ((GraphicsPanelTree)MainWindow_Panel_Graph).processData(data);
    System.out.println(data);
    }//GEN-LAST:event_MainWindow_TextFiels_AddNumActionPerformed

    private void MainWindow_Button_ShowTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_Button_ShowTableActionPerformed
    String data = MainWindow_TextFiels_AddNum.getText();    

    ((GraphicsPanelTree)MainWindow_Panel_Graph).processData(data);
    System.out.println(data);
    }//GEN-LAST:event_MainWindow_Button_ShowTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainWindow_Button_ShowTable;
    private javax.swing.JLabel MainWindow_Label_Warning;
    private javax.swing.JPanel MainWindow_Panel_Graph;
    private javax.swing.JTextField MainWindow_TextFiels_AddNum;
    // End of variables declaration//GEN-END:variables
}
