/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vbinarysearchtree;

/**
 *
 * @author skyla
 */
public class MainWindow2 extends javax.swing.JFrame {
        
    final private ViperBST tree;
    /**
     * Creates new form BSTGrapgics
     */
    public MainWindow2() {
        initComponents();
        tree = new ViperBST();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainWindow2_Frame_tree_panel = new GraphicPanel();
        MainWindow2_TextField_Add = new javax.swing.JTextField();
        MainWindow2_button_add = new javax.swing.JButton();
        MainWindow2_label_stats = new javax.swing.JLabel();
        MainWindow2_label_levels = new javax.swing.JLabel();
        MainWindow2_label_string = new javax.swing.JLabel();
        MainWindow2_label_leaves = new javax.swing.JLabel();
        MainWindow2_textFiled_string = new javax.swing.JTextField();
        MainWindow2_label_nodes = new javax.swing.JLabel();
        MainWindow2_textFiled_preOrder = new javax.swing.JTextField();
        MainWindow2_label_full = new javax.swing.JLabel();
        MainWindow2_label_preOrder = new javax.swing.JLabel();
        MainWindow2_label_complete = new javax.swing.JLabel();
        MainWindow2_textFiled_InOrder = new javax.swing.JTextField();
        MainWindow2_textLabel_height = new javax.swing.JTextField();
        MainWindow2_label_PostOrder = new javax.swing.JLabel();
        MainWindow2_textField_levels = new javax.swing.JTextField();
        MainWindow2_textField_PostOrder = new javax.swing.JTextField();
        MainWindow2_textField_leaves = new javax.swing.JTextField();
        MainWindow2_label_inOder = new javax.swing.JLabel();
        MainWindow2_textField_Nodes = new javax.swing.JTextField();
        MainWindow2_textField_isFull = new javax.swing.JTextField();
        MainWindow2_label_height = new javax.swing.JLabel();
        MainWindow2_textField_isComplete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainWindow2_Frame_tree_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainWindow2_Frame_tree_panelLayout = new javax.swing.GroupLayout(MainWindow2_Frame_tree_panel);
        MainWindow2_Frame_tree_panel.setLayout(MainWindow2_Frame_tree_panelLayout);
        MainWindow2_Frame_tree_panelLayout.setHorizontalGroup(
            MainWindow2_Frame_tree_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MainWindow2_Frame_tree_panelLayout.setVerticalGroup(
            MainWindow2_Frame_tree_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        MainWindow2_TextField_Add.setMinimumSize(new java.awt.Dimension(100, 23));
        MainWindow2_TextField_Add.setPreferredSize(new java.awt.Dimension(100, 23));

        MainWindow2_button_add.setText("ADD");
        MainWindow2_button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow2_button_addActionPerformed(evt);
            }
        });

        MainWindow2_label_stats.setText("STATS");

        MainWindow2_label_levels.setText("Levels");

        MainWindow2_label_string.setText("String");

        MainWindow2_label_leaves.setText("Leaves");

        MainWindow2_textFiled_string.setEditable(false);
        MainWindow2_textFiled_string.setBackground(new java.awt.Color(255, 255, 255));

        MainWindow2_label_nodes.setText("Nodes");

        MainWindow2_textFiled_preOrder.setEditable(false);
        MainWindow2_textFiled_preOrder.setBackground(new java.awt.Color(255, 255, 255));

        MainWindow2_label_full.setText("Full?");

        MainWindow2_label_preOrder.setText("Pre Order");

        MainWindow2_label_complete.setText("Complete?");

        MainWindow2_textFiled_InOrder.setEditable(false);
        MainWindow2_textFiled_InOrder.setBackground(new java.awt.Color(255, 255, 255));

        MainWindow2_textLabel_height.setEditable(false);
        MainWindow2_textLabel_height.setBackground(new java.awt.Color(255, 255, 255));
        MainWindow2_textLabel_height.setText("     ");

        MainWindow2_label_PostOrder.setText("Post Order");

        MainWindow2_textField_levels.setEditable(false);
        MainWindow2_textField_levels.setBackground(new java.awt.Color(255, 255, 255));
        MainWindow2_textField_levels.setText("     ");

        MainWindow2_textField_PostOrder.setEditable(false);
        MainWindow2_textField_PostOrder.setBackground(new java.awt.Color(255, 255, 255));

        MainWindow2_textField_leaves.setEditable(false);
        MainWindow2_textField_leaves.setBackground(new java.awt.Color(255, 255, 255));
        MainWindow2_textField_leaves.setText("     ");

        MainWindow2_label_inOder.setText("In Order");

        MainWindow2_textField_Nodes.setEditable(false);
        MainWindow2_textField_Nodes.setBackground(new java.awt.Color(255, 255, 255));
        MainWindow2_textField_Nodes.setText("     ");

        MainWindow2_textField_isFull.setEditable(false);
        MainWindow2_textField_isFull.setBackground(new java.awt.Color(255, 255, 255));
        MainWindow2_textField_isFull.setText("          ");

        MainWindow2_label_height.setText("Height");

        MainWindow2_textField_isComplete.setEditable(false);
        MainWindow2_textField_isComplete.setBackground(new java.awt.Color(255, 255, 255));
        MainWindow2_textField_isComplete.setText("          ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(MainWindow2_label_stats))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MainWindow2_label_complete)
                                        .addGap(18, 18, 18)
                                        .addComponent(MainWindow2_textField_isComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MainWindow2_label_nodes)
                                        .addGap(40, 40, 40)
                                        .addComponent(MainWindow2_textField_Nodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MainWindow2_label_leaves)
                                            .addComponent(MainWindow2_label_full)
                                            .addComponent(MainWindow2_label_height)
                                            .addComponent(MainWindow2_label_levels))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MainWindow2_textField_levels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MainWindow2_textField_leaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MainWindow2_textField_isFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MainWindow2_textLabel_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(MainWindow2_textFiled_string, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(MainWindow2_label_string)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(MainWindow2_textFiled_InOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(MainWindow2_textFiled_preOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(MainWindow2_textField_PostOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(MainWindow2_label_inOder)
                                .addGap(189, 189, 189)
                                .addComponent(MainWindow2_label_preOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MainWindow2_label_PostOrder)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MainWindow2_Frame_tree_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MainWindow2_TextField_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MainWindow2_button_add)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainWindow2_TextField_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainWindow2_button_add))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(MainWindow2_label_stats)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MainWindow2_label_height)
                            .addComponent(MainWindow2_textLabel_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MainWindow2_label_levels)
                            .addComponent(MainWindow2_textField_levels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MainWindow2_label_leaves)
                            .addComponent(MainWindow2_textField_leaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MainWindow2_textField_Nodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MainWindow2_label_nodes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MainWindow2_textField_isFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MainWindow2_label_full))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MainWindow2_textField_isComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MainWindow2_label_complete))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainWindow2_Frame_tree_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MainWindow2_label_string)
                                    .addComponent(MainWindow2_label_inOder))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MainWindow2_textFiled_string, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MainWindow2_textFiled_InOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MainWindow2_label_preOrder)
                                    .addComponent(MainWindow2_label_PostOrder))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MainWindow2_textFiled_preOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MainWindow2_textField_PostOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainWindow2_button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow2_button_addActionPerformed
        //graphic update
        tree.add(Integer.valueOf(MainWindow2_TextField_Add.getText()));
        ((GraphicPanel) MainWindow2_Frame_tree_panel).processData(tree);
        
        updateStats();
        clean();
    }//GEN-LAST:event_MainWindow2_button_addActionPerformed

    private void clean() {
        MainWindow2_TextField_Add.setText("");
    }
    
    private void updateStats() {
        //stats
        MainWindow2_textLabel_height.setText(tree.getHeight() + "");
        MainWindow2_textField_levels.setText(tree.getNumLevels() + "");
        MainWindow2_textField_leaves.setText(tree.getNumLeaves() + "");
        MainWindow2_textField_Nodes.setText(tree.getNumNodes() + "");
        MainWindow2_textField_isFull.setText(tree.isFull() + "");
        MainWindow2_textField_isComplete.setText(tree.isComplete() + "");
        
        //strings
        MainWindow2_textFiled_string.setText(tree.toString());
        MainWindow2_textFiled_InOrder.setText(tree.inOrder());
        MainWindow2_textFiled_preOrder.setText(tree.preOrder());
        MainWindow2_textField_PostOrder.setText(tree.postOrder());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainWindow2_Frame_tree_panel;
    private javax.swing.JTextField MainWindow2_TextField_Add;
    private javax.swing.JButton MainWindow2_button_add;
    private javax.swing.JLabel MainWindow2_label_PostOrder;
    private javax.swing.JLabel MainWindow2_label_complete;
    private javax.swing.JLabel MainWindow2_label_full;
    private javax.swing.JLabel MainWindow2_label_height;
    private javax.swing.JLabel MainWindow2_label_inOder;
    private javax.swing.JLabel MainWindow2_label_leaves;
    private javax.swing.JLabel MainWindow2_label_levels;
    private javax.swing.JLabel MainWindow2_label_nodes;
    private javax.swing.JLabel MainWindow2_label_preOrder;
    private javax.swing.JLabel MainWindow2_label_stats;
    private javax.swing.JLabel MainWindow2_label_string;
    private javax.swing.JTextField MainWindow2_textField_Nodes;
    private javax.swing.JTextField MainWindow2_textField_PostOrder;
    private javax.swing.JTextField MainWindow2_textField_isComplete;
    private javax.swing.JTextField MainWindow2_textField_isFull;
    private javax.swing.JTextField MainWindow2_textField_leaves;
    private javax.swing.JTextField MainWindow2_textField_levels;
    private javax.swing.JTextField MainWindow2_textFiled_InOrder;
    private javax.swing.JTextField MainWindow2_textFiled_preOrder;
    private javax.swing.JTextField MainWindow2_textFiled_string;
    private javax.swing.JTextField MainWindow2_textLabel_height;
    // End of variables declaration//GEN-END:variables
}
